services:
  bora-ora-backend:
    build:
      context: './docker'
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Seoul"
    container_name: bora-ora-backend
    hostname: bora-ora-backend
    domainname: localdomain
    ports:
      - "3030:3030"
    stdin_open: true
    tty: true
    volumes:
      - .:/Workspaces:rw
      - ./docker/storage:/tmp/storage
    #    command:
    #      - /usr/local/bin/start.sh
    networks:
      - bora-networks

networks:
  bora-networks:
    driver: bridge
