export default [
    {
        id: `010`,
        name: `클라이언트 구분`,
        description: `클라이언트 종류 코드`,
        list: [
            { id: `010`, name: `iOS`, description: `아이폰 사용자` },
            { id: `020`, name: `android`, description: `안드로이드 사용자` },
            { id: `030`, name: `web`, description: `웹 사용자` },
        ],
    },
    {
        id: `020`,
        name: `회원 상태`,
        list: [
            { id: `010`, name: `회원가입(인증이전)` },
            { id: `020`, name: `인증완료` },
            { id: `030`, name: `block 상태` },
        ],
    },
    {
        id: `030`,
        name: `회원 레벨`,
        list: [
            { id: `010`, name: `일반 사용자` },
            { id: `020`, name: `매니저` },
            { id: `090`, name: `관리자` },
            { id: `999`, name: `최고 관리자` },
        ],
    },
    {
        id: `040`,
        name: `유형`,
        list: [
            { id: `010`, name: `얼리버드` },
            { id: `020`, name: `여자매치` },
            { id: `030`, name: `스타터` },
            { id: `040`, name: `챌린지` },
            { id: `050`, name: `시작하기` },
        ],
    },
    {
        id: `050`,
        name: `팀`,
        list: [
            { id: `010`, name: `플랩 팀 리그` },
            { id: `020`, name: `자체전` },
            { id: `030`, name: `대회 준비` },
            { id: `040`, name: `팀 매칭` },
            { id: `050`, name: `5 VS 5 풋살` },
            { id: `060`, name: `전문 코치` },
            { id: `070`, name: `함께 성장` },
        ],
    },
    {
        id: `060`,
        name: `구장 크기`,
        list: [
            { id: `010`, name: `3 VS 3` },
            { id: `020`, name: `4 VS 4` },
            { id: `030`, name: `5 VS 5` },
            { id: `040`, name: `6 VS 6` },
            { id: `050`, name: `8 VS 8` },
            { id: `060`, name: `11 VS 11` },
        ],
    },
    {
        id: `070`,
        name: `실내외`,
        list: [
            { id: `010`, name: `실내` },
            { id: `020`, name: `실외` },
        ],
    },
    {
        id: `080`,
        name: `바닥종류`,
        list: [
            { id: `010`, name: `인조잔디` },
            { id: `020`, name: `천연잔디` },
            { id: `030`, name: `인도어` },
            { id: `040`, name: `모래` },
        ],
    },
    {
        id: `090`,
        name: `지역`,
        list: [
            { id: `999`, name: `모든 지역` },
            { id: `010`, name: `서울` },
            { id: `020`, name: `경기` },
            { id: `030`, name: `인천` },
            { id: `040`, name: `강원` },
            { id: `050`, name: `대전` },
            { id: `060`, name: `충남/세종` },
            { id: `070`, name: `충북` },
            { id: `080`, name: `대구` },
            { id: `090`, name: `경북` },
            { id: `100`, name: `부산` },
            { id: `110`, name: `울산` },
            { id: `120`, name: `경남` },
            { id: `130`, name: `광주` },
            { id: `140`, name: `전남` },
            { id: `150`, name: `전북` },
            { id: `160`, name: `제주` },
        ],
    },
    {
        id: `100`,
        name: `매치 상태`,
        list: [
            { id: `010`, name: `신청가능` },
            { id: `020`, name: `마감` },
            { id: `099`, name: `마감임박` },
        ],
    },
    {
        id: `110`,
        name: `성별`,
        list: [
            { id: `010`, name: `남자` },
            { id: `020`, name: `여자` },
            { id: `030`, name: `남녀 모두` },
        ],
    },
    {
        id: `120`,
        name: `매치 레벨`,
        list: [
            { id: `999`, name: `모든 레벨` },
            { id: `010`, name: `아마추어1 이하` },
            { id: `020`, name: `아마추어2 이상` },
        ],
    },
    {
        id: `130`,
        name: `팀 종목`,
        list: [
            { id: `010`, name: `풋살` },
            { id: `020`, name: `축구` },
            { id: `030`, name: `축구 + 풋살` },
        ],
    },
    {
        id: `140`,
        name: `팀 레벨`,
        list: [
            { id: `999`, name: `실력무관` },
            { id: `010`, name: `스타터` },
            { id: `020`, name: `비기너` },
            { id: `030`, name: `아마추어` },
            { id: `040`, name: `세미프로` },
            { id: `050`, name: `프로` },
        ],
    },
    {
        id: `150`,
        name: `나이`,
        list: [
            { id: `010`, name: `10대` },
            { id: `020`, name: `20대` },
            { id: `030`, name: `30대` },
            { id: `040`, name: `40대` },
            { id: `050`, name: `50대` },
            { id: `060`, name: `60대 이상` },
        ],
    },
    {
        id: `160`,
        name: `시간대`,
        list: [
            { id: `010`, name: `아침` },
            { id: `020`, name: `낮` },
            { id: `030`, name: `저녁` },
            { id: `040`, name: `심야` },
        ],
    },
    {
        id: `170`,
        name: `요일`,
        list: [
            { id: `010`, name: `월` },
            { id: `020`, name: `화` },
            { id: `030`, name: `수` },
            { id: `040`, name: `목` },
            { id: `050`, name: `금` },
            { id: `060`, name: `토` },
            { id: `070`, name: `일` },
        ],
    },
    {
        id: `180`,
        name: `선호시간`,
        list: [
            { id: `010`, name: `06:00` },
            { id: `020`, name: `08:00` },
            { id: `030`, name: `10:00` },
            { id: `040`, name: `12:00` },
            { id: `050`, name: `14:00` },
            { id: `060`, name: `16:00` },
            { id: `070`, name: `18:00` },
            { id: `080`, name: `20:00` },
            { id: `090`, name: `22:00` },
            { id: `100`, name: `24:00` },
            { id: `110`, name: `02:00` },
            { id: `120`, name: `04:00` },
        ],
    },
    {
        id: `190`,
        name: `활동반경`,
        list: [
            { id: `010`, name: `10km` },
            { id: `020`, name: `20km` },
            { id: `030`, name: `30km` },
            { id: `040`, name: `40km` },
        ],
    },
];
